## 避免和 server 工程端口冲突
server:
  port: 8081

## Dubbo 服务消费者配置
spring:
  dubbo:
    application:
      name: admin
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.hyc.controller.product